/**
 * Auro Summary Builder
 * 
 * Generates structured summaries of lead interactions across WhatsApp and Voice.
 */

interface SummaryData {
    leadName: string;
    leadPhone: string;
    leadEmail?: string;
    budget?: string;
    location?: string;
    propertyType?: string;
    whatsappTranscript?: string;
    voiceSummary?: string;
    voiceRecordingUrl?: string;
    meetingDateTime?: string;
    meetingUrl?: string;
}

/**
 * Generates a deterministic, plain-text summary of the lead's engagement.
 * @param data The collected data from WhatsApp and Voice interactions.
 * @returns A formatted string prefixed with "AURO SUMMARY".
 */
export function generateAuroSummary(data: SummaryData): string {
    const lines: string[] = [];

    lines.push("AURO SUMMARY");
    lines.push("====================================");
    lines.push(`Lead: ${data.leadName}`);
    lines.push(`Phone: ${data.leadPhone}`);
    if (data.leadEmail) lines.push(`Email: ${data.leadEmail}`);
    lines.push("------------------------------------");

    lines.push("QUALIFICATION DETAILS:");
    lines.push(`- Budget: ${data.budget || 'Not specified'}`);
    lines.push(`- Preferred Area: ${data.location || 'Not specified'}`);
    lines.push(`- Property Type: ${data.propertyType || 'Not specified'}`);
    lines.push("------------------------------------");

    if (data.meetingDateTime) {
        lines.push("MEETING CONFIRMED:");
        lines.push(`- Date/Time: ${data.meetingDateTime}`);
        if (data.meetingUrl) lines.push(`- Link: ${data.meetingUrl}`);
        lines.push("------------------------------------");
    }

    if (data.voiceSummary) {
        lines.push("VOICE INTERACTION SUMMARY:");
        lines.push(data.voiceSummary);
        if (data.voiceRecordingUrl) {
            lines.push("");
            lines.push(`Recording: ${data.voiceRecordingUrl}`);
        }
        lines.push("------------------------------------");
    }

    if (data.whatsappTranscript) {
        lines.push("WHATSAPP CONVERSATION HIGHLIGHTS:");
        lines.push(data.whatsappTranscript);
        lines.push("------------------------------------");
    }

    lines.push("Generated by AURO AI Agent");

    return lines.join("\n");
}
